### ISSUE TITLE
🎉Enhance `HiModal` component to a common mask component

### ISSUE THREAD

**Issue by JounQin** [Raiyee/EasyHi#2]
For now, `HiModal` has support `Bootstrap Modal` very well, and actually it could be used to do a lot of things.

Because the `component` list is dynamically added and fully customized, so it is possible to set the component item to be a `tip`, `confirm` or sth else.

Of course, `tip` or `confirm` component could be another instance of `ModalItem`.

Finally, we could write another `HiModal` (or call it `HiDialog`) component which won't depend on `Bootstrap UI`.

Just do it!

**Comment by xwwLmm** [comment]
It's ok
